### ISSUE TITLE
version selector appears to be broken

### ISSUE THREAD

**Issue by Djfe** [freifunk-gluon/census-exporter#29]
selecting a major version (or version) doesn't appear to be influencing the diagrams on the dashboard

tested on Firefox for Android (117.1)

**Comment by herbetom** [comment]
The "Major Version" Selector only influences which versions are selectable in the "Version" Selector.

**Comment by Djfe** [comment]
ok but that one doesn't work either. it shows me all nodes below, no matter what I choose 🤔
43055

**Comment by herbetom** [comment]
The "Version" Selector only affects the "Per Version" Graph/Section.

**Comment by Djfe** [comment]
ah, that makes so much sense. Now I understand all the sections, thank you.
I missed this likely due to using the dashboard on mobile 🙈
